#!/usr/bin/env bash
# SELD-VLA (pi0, SlotEncoder path) end-to-end pipeline for find_hidden_object_open:
#   a sound comes from an object hidden in one of two cabinets' top/bottom
#   drawers; the robot must open the correct drawer. The sound source (the
#   hidden object) encodes both azimuth (which cabinet) and elevation (which
#   drawer), so this is a single-source spatial-localization task like
#   select_radio — same slots_uv audio path, one task, no combine step.
#
# Audio reaches pi0 via audio_mode="slots_uv": class words + loudness go into
# the prompt text and (u,v)+energy+conf feed the continuous SlotEncoder token.
# Training uses the openpi backbone (LoRA on PaliGemma by default).
#
# REQUIRED env: OPENPI_PI0_JAX_WEIGHT, OPENPI_PI0_PYTORCH_WEIGHT
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/home/rllab/Desktop/AVLABench}"
OPENPI_ROOT="${OPENPI_ROOT:-${REPO_ROOT}/third_party/openpi}"
UV_CACHE_DIR="${UV_CACHE_DIR:-/tmp/uv-cache}"
CONDA_ENV="${CONDA_ENV:-vlabench}"
PY="conda run -n ${CONDA_ENV} --no-capture-output python"
# Conversion MUST run in the openpi venv (lerobot 0.1.0 -> v2.1 format the
# openpi training loader reads).
CONVERT_PY=(env "UV_CACHE_DIR=${UV_CACHE_DIR}" uv --project "${OPENPI_ROOT}" run python)

TAXONOMY="${TAXONOMY:-${REPO_ROOT}/class_taxonomy.yaml}"
TASK="find_hidden_object_open"
REPO_ID="${REPO_ID:-local/avla_find_hidden}"

# Instruction — MUST match VLABench config manager (FIND_HIDDEN_OPEN_INSTRUCTION)
# and eval_smolvla_audio.FIND_HIDDEN_INSTRUCTION. Written to every episode's
# LeRobot `task` field (so we do NOT use --use-episode-instruction; the stored
# per-episode instruction may be an older phrasing).
INSTRUCTION="${INSTRUCTION:-Open the drawer of the cabinet that contains the object making the sound.}"

# ---- data locations --------------------------------------------------------
# Source HDF5 produced by sh/gen_find_hidden_balance.sh
GEN_ROOT="${GEN_ROOT:-${REPO_ROOT}/dataset_find_hidden_lerobot_src}"
SRC_DIR="${SRC_DIR:-${GEN_ROOT}/${TASK}}"
LEROBOT_DIR="${LEROBOT_DIR:-${REPO_ROOT}/dataset_find_hidden_lerobot}"

# ---- stage switches --------------------------------------------------------
DO_GENERATE="${DO_GENERATE:-0}"   # data already generated by gen_find_hidden_balance.sh
DO_CONVERT="${DO_CONVERT:-1}"
DO_NORM="${DO_NORM:-1}"
DO_TRAIN="${DO_TRAIN:-1}"
DO_EVAL="${DO_EVAL:-1}"

# ---- generation (optional) -------------------------------------------------
PER_SLOT="${PER_SLOT:-120}"
MAX_PARALLEL="${MAX_PARALLEL:-2}"

# ---- conversion ------------------------------------------------------------
TOP_K="${TOP_K:-3}"
IMAGE_SIZE="${IMAGE_SIZE:-224}"
VCODEC="${VCODEC:-h264}"
# Write the *achieved* EE pose into observation.state instead of the commanded
# target. Without this state == action, and the policy learns the shortcut
# action[0] = state, which misfires at eval where state lags the command.
USE_REAL_STATE="${USE_REAL_STATE:-1}"

# ---- training (openpi) -----------------------------------------------------
POLICY_CONFIG="${POLICY_CONFIG:-pi0_ft_vlabench_find_hidden_lora}"
EXP_NAME="${EXP_NAME:-pi0_find_hidden_lora}"
OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/outputs/pi0_find_hidden_lora}"
TRAIN_STEPS="${TRAIN_STEPS:-60000}"
SAVE_INTERVAL="${SAVE_INTERVAL:-10000}"
BATCH_SIZE="${BATCH_SIZE:-32}"
NUM_WORKERS="${NUM_WORKERS:-16}"
NUM_GPUS="${NUM_GPUS:-1}"
RESUME="${RESUME:-0}"
# lr_schedule.decay_steps defaults to the config's built-in 60000. For short
# runs pass DECAY_STEPS=TRAIN_STEPS so the cosine schedule fully decays.
DECAY_STEPS="${DECAY_STEPS:-}"
# Also exposed (the config's built-in is 2000, which is 18% of a short run and
# leaves too little post-warmup schedule; the KISTI script exposes these too).
PEAK_LR="${PEAK_LR:-}"
WARMUP_STEPS="${WARMUP_STEPS:-}"
VLM_LORA="${VLM_LORA:-1}"
# Full/partial fine-tune of PaliGemma. LoRA (VLM_LORA=1) takes precedence, so
# set VLM_LORA=0 to use FREEZE_PALIGEMMA (train_pytorch.py).
FREEZE_PALIGEMMA="${FREEZE_PALIGEMMA:-0}"
# Two-phase fine-tune (src/staged_freeze), same knobs as the KISTI script: train
# everything (PaliGemma LoRA + action expert + heads) up to the switch, then
# freeze the whole PaliGemma tower (LoRA adapters included) and continue with the
# action expert only. Empty = off. Set exactly one of FRAC (0<f<1) or STEP.
FREEZE_LLM_AT_FRAC="${FREEZE_LLM_AT_FRAC:-}"
FREEZE_LLM_AT_STEP="${FREEZE_LLM_AT_STEP:-}"
FREEZE_LLM_AUDIO_HEADS="${FREEZE_LLM_AUDIO_HEADS:-0}"
LORA_RANK="${LORA_RANK:-16}"
LORA_ALPHA="${LORA_ALPHA:-16}"
LORA_DROPOUT="${LORA_DROPOUT:-0.05}"
LORA_TARGETS="${LORA_TARGETS:-attn,mlp}"
WANDB_MODE="${WANDB_MODE:-offline}"

# ---- eval ------------------------------------------------------------------
EVAL_N="${EVAL_N:-100}"
EVAL_MAX_LEN="${EVAL_MAX_LEN:-250}"
EVAL_HORIZON="${EVAL_HORIZON:-5}"
EVAL_STEP="${EVAL_STEP:-}"
EVAL_NOISE_AZ_STD="${EVAL_NOISE_AZ_STD:-0}"
EVAL_NOISE_EL_STD="${EVAL_NOISE_EL_STD:-0}"
EVAL_NOISE_CONF_MIN="${EVAL_NOISE_CONF_MIN:-1.0}"
EVAL_NOISE_CONF_MAX="${EVAL_NOISE_CONF_MAX:-1.0}"
EVAL_NOISE_CLASS_FLIP_PROB="${EVAL_NOISE_CLASS_FLIP_PROB:-0}"
EVAL_NOISE_ENERGY_STD="${EVAL_NOISE_ENERGY_STD:-0}"

cd "${REPO_ROOT}"

cat <<EOF
[find-hidden] gen=${DO_GENERATE} convert=${DO_CONVERT} norm=${DO_NORM} train=${DO_TRAIN} eval=${DO_EVAL}
          src_hdf5 = ${SRC_DIR}
          lerobot  = ${LEROBOT_DIR}   repo_id=${REPO_ID}
          config   = ${POLICY_CONFIG}  output=${OUTPUT_DIR}
          steps=${TRAIN_STEPS} batch=${BATCH_SIZE} lora=${VLM_LORA}
          instruction="${INSTRUCTION}"
EOF

# ---------------------------------------------------------------------------
# [1] (optional) generate balanced oracle HDF5
# ---------------------------------------------------------------------------
if [[ "${DO_GENERATE}" == "1" ]]; then
    echo "==================== [1] generate balanced dataset ===================="
    PER_SLOT="${PER_SLOT}" MAX_PARALLEL="${MAX_PARALLEL}" \
    GEN_ROOT="${GEN_ROOT}" bash sh/gen_find_hidden_balance.sh
fi

# ---------------------------------------------------------------------------
# [2] convert HDF5 -> LeRobot (fixed instruction; writes energy + uv columns)
# ---------------------------------------------------------------------------
if [[ "${DO_CONVERT}" == "1" ]]; then
    echo "==================== [2] convert -> LeRobot ===================="
    [[ -d "${SRC_DIR}" ]] || { echo "[err] missing ${SRC_DIR} (run generation first)"; exit 1; }
    rm -rf "${LEROBOT_DIR}"
    convert_extra=()
    [[ "${USE_REAL_STATE}" == "1" ]] && convert_extra+=(--use-real-state)
    "${CONVERT_PY[@]}" src/data/convert_hdf5_to_lerobot.py \
        "${convert_extra[@]}" \
        --src-dir "${SRC_DIR}" \
        --out-dir "${LEROBOT_DIR}" \
        --repo-id "${REPO_ID}" \
        --fps 10 \
        --top-k "${TOP_K}" \
        --image-h "${IMAGE_SIZE}" \
        --image-w "${IMAGE_SIZE}" \
        --vcodec "${VCODEC}" \
        --oracle-mode \
        --instruction "${INSTRUCTION}"
fi

# Symlink the local LeRobot dataset into HF_LEROBOT_HOME so openpi's loader
# skips the HF API (same trick as the other openpi pipelines).
LEROBOT_CACHE="${HF_LEROBOT_HOME:-${HOME}/.cache/huggingface/lerobot}/${REPO_ID}"
mkdir -p "$(dirname "${LEROBOT_CACHE}")"
ln -sfn "${LEROBOT_DIR}" "${LEROBOT_CACHE}"

# ---------------------------------------------------------------------------
# [3] compute normalization stats for the config
# ---------------------------------------------------------------------------
if [[ "${DO_NORM}" == "1" ]]; then
    echo "==================== [3] compute norm stats ===================="
    env "UV_CACHE_DIR=${UV_CACHE_DIR}" \
        "OPENPI_PI0_JAX_WEIGHT=${OPENPI_PI0_JAX_WEIGHT:-}" \
        "OPENPI_PI0_PYTORCH_WEIGHT=${OPENPI_PI0_PYTORCH_WEIGHT:-}" \
        "OPENPI_PI05_PYTORCH_WEIGHT=${OPENPI_PI05_PYTORCH_WEIGHT:-}" \
        uv --project "${OPENPI_ROOT}" run python \
        "${OPENPI_ROOT}/scripts/compute_norm_stats.py" --config-name "${POLICY_CONFIG}"
fi

# ---------------------------------------------------------------------------
# [4] train pi0 (LoRA on PaliGemma by default)
# ---------------------------------------------------------------------------
if [[ "${DO_TRAIN}" == "1" ]]; then
    echo "==================== [4] train ${POLICY_CONFIG} ===================="
    if [[ -z "${OPENPI_PI0_JAX_WEIGHT:-}" || -z "${OPENPI_PI0_PYTORCH_WEIGHT:-}" ]]; then
        echo "[err] OPENPI_PI0_JAX_WEIGHT and OPENPI_PI0_PYTORCH_WEIGHT must be set."; exit 1
    fi
    resume_flag=(); [[ "${RESUME}" == "1" ]] && resume_flag+=(--resume)
    decay_flag=(); [[ -n "${DECAY_STEPS}" ]] && decay_flag+=(--lr_schedule.decay_steps "${DECAY_STEPS}")
    [[ -n "${PEAK_LR}" ]]      && decay_flag+=(--lr_schedule.peak_lr "${PEAK_LR}")
    [[ -n "${WARMUP_STEPS}" ]] && decay_flag+=(--lr_schedule.warmup_steps "${WARMUP_STEPS}")
    launcher=()
    (( NUM_GPUS > 1 )) && launcher=(torchrun --standalone --nnodes=1 --nproc_per_node="${NUM_GPUS}")
    lora_env=()
    if [[ "${VLM_LORA}" == "1" ]]; then
        lora_env=(
            "OPENPI_PALIGEMMA_LORA=1"
            "OPENPI_LORA_RANK=${LORA_RANK}"
            "OPENPI_LORA_ALPHA=${LORA_ALPHA}"
            "OPENPI_LORA_DROPOUT=${LORA_DROPOUT}"
            "OPENPI_LORA_TARGETS=${LORA_TARGETS}"
        )
    fi
    env "UV_CACHE_DIR=${UV_CACHE_DIR}" \
        "WANDB_MODE=${WANDB_MODE}" \
        "OPENPI_PI0_JAX_WEIGHT=${OPENPI_PI0_JAX_WEIGHT}" \
        "OPENPI_PI0_PYTORCH_WEIGHT=${OPENPI_PI0_PYTORCH_WEIGHT}" \
        "OPENPI_PI05_PYTORCH_WEIGHT=${OPENPI_PI05_PYTORCH_WEIGHT:-}" \
        "PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True" \
        "OPENPI_FREEZE_PALIGEMMA=${FREEZE_PALIGEMMA}" \
        "OPENPI_FREEZE_LLM_AT_FRAC=${FREEZE_LLM_AT_FRAC}" \
        "OPENPI_FREEZE_LLM_AT_STEP=${FREEZE_LLM_AT_STEP}" \
        "OPENPI_FREEZE_LLM_AUDIO_HEADS=${FREEZE_LLM_AUDIO_HEADS}" \
        "${lora_env[@]}" \
        uv --project "${OPENPI_ROOT}" run \
        "${launcher[@]}" python "${OPENPI_ROOT}/scripts/train_pytorch.py" \
        "${POLICY_CONFIG}" \
        --exp_name "${EXP_NAME}" \
        --num_train_steps "${TRAIN_STEPS}" \
        --batch_size "${BATCH_SIZE}" \
        --num_workers "${NUM_WORKERS}" \
        --save_interval "${SAVE_INTERVAL}" \
        --checkpoint_base_dir "${OUTPUT_DIR}" \
        "${resume_flag[@]}" \
        "${decay_flag[@]}"
fi

# ---------------------------------------------------------------------------
# [5] eval (audio-mode slots_uv, oracle)
# ---------------------------------------------------------------------------
if [[ "${DO_EVAL}" == "1" ]]; then
    CKPT_ROOT="${OUTPUT_DIR}/${POLICY_CONFIG}/${EXP_NAME}"
    if [[ -n "${EVAL_STEP}" ]]; then
        POLICY_DIR="${CKPT_ROOT}/${EVAL_STEP}"
    else
        POLICY_DIR="$(ls -dt ${CKPT_ROOT}/*/ 2>/dev/null | head -1)"
    fi
    POLICY_DIR="${POLICY_DIR%/}"
    if [[ -z "${POLICY_DIR}" || ! -d "${POLICY_DIR}" ]]; then
        echo "[err] no checkpoint under ${CKPT_ROOT}"; exit 1
    fi
    echo "==================== [5] eval ${TASK} @ ${POLICY_DIR} ===================="
    # This path calls eval_pi05_audio.sh directly, so it does NOT infer the mic
    # camera from the checkpoint the way sh/eval_pi05_find_hidden.sh does. Since
    # the v3 rebuild moved the binaural listener camera 2 -> 1, a pre-v3
    # checkpoint evaluated here silently gets the wrong (u,v) reference frame.
    if [[ -z "${VLABENCH_MIC_CAM:-}" ]]; then
        echo "[warn] VLABENCH_MIC_CAM is unset. Pre-v3 checkpoints need =2."
        echo "[warn] Prefer: POLICY_DIR=... bash sh/eval_pi05_find_hidden.sh (infers it)."
    else
        echo "[eval] VLABENCH_MIC_CAM=${VLABENCH_MIC_CAM}"
    fi
    EVAL_DIR="${REPO_ROOT}/outputs/eval_find_hidden" TASK_NAME="${TASK}" TAXONOMY="${TAXONOMY}" \
    LOCAL=1 POLICY_CONFIG="${POLICY_CONFIG}" POLICY_DIR="${POLICY_DIR}" \
    OPENPI_ROOT="${OPENPI_ROOT}" AUDIO_MODE="slots_uv" EVAL_MODE="oracle" \
    EVAL_N="${EVAL_N}" EVAL_MAX_LEN="${EVAL_MAX_LEN}" EVAL_HORIZON="${EVAL_HORIZON}" \
    TOP_K="${TOP_K}" \
    NOISE_AZ_STD="${EVAL_NOISE_AZ_STD}" NOISE_EL_STD="${EVAL_NOISE_EL_STD}" \
    NOISE_CONF_MIN="${EVAL_NOISE_CONF_MIN}" NOISE_CONF_MAX="${EVAL_NOISE_CONF_MAX}" \
    NOISE_CLASS_FLIP_PROB="${EVAL_NOISE_CLASS_FLIP_PROB}" \
    NOISE_ENERGY_STD="${EVAL_NOISE_ENERGY_STD}" \
    bash sh/eval_pi05_audio.sh
fi

echo "==================== [done] find_hidden pi0 slots_uv pipeline ===================="
echo "  lerobot     : ${LEROBOT_DIR}"
echo "  checkpoints : ${OUTPUT_DIR}/${POLICY_CONFIG}/${EXP_NAME}"
